/**
 * Bootstrap Icons (react-icons/bs) for category picker.
 * @see https://react-icons.github.io/react-icons/icons/bs/
 */
export const DEFAULT_CATEGORY_ICON = 'BsBox';

export const CATEGORY_ICON_LIBRARY = [
  // Electronics & tech
  'BsPhone',
  'BsPhoneFill',
  'BsTablet',
  'BsTabletFill',
  'BsLaptop',
  'BsLaptopFill',
  'BsDisplay',
  'BsTv',
  'BsSmartwatch',
  'BsCamera',
  'BsCameraVideo',
  'BsCameraReels',
  'BsController',
  'BsJoystick',
  'BsHeadphones',
  'BsEarbuds',
  'BsSpeaker',
  'BsMic',
  'BsMusicNote',
  'BsMusicNoteBeamed',
  'BsDisc',
  'BsMouse',
  'BsMouse2',
  'BsKeyboard',
  'BsKeyboardFill',
  'BsUsbDrive',
  'BsHdd',
  'BsSdCard',
  'BsMemory',
  'BsCpu',
  'BsGpuCard',
  'BsMotherboard',
  'BsRouter',
  'BsWifi',
  'BsBluetooth',
  'BsBatteryCharging',
  'BsBatteryFull',
  'BsPlug',
  'BsLightning',
  'BsLightningCharge',
  'BsPrinter',
  'BsPrinterFill',
  'BsQrCode',
  'BsUpc',
  // Fashion & accessories
  'BsEyeglasses',
  'BsSunglasses',
  'BsWatch',
  'BsGem',
  'BsDiamond',
  'BsHandbag',
  'BsBackpack',
  'BsBag',
  'BsBagCheck',
  'BsBagPlus',
  'BsScissors',
  'BsBrush',
  'BsPalette',
  'BsEyedropper',
  'BsPaintBucket',
  // Food & beverage
  'BsCup',
  'BsCupStraw',
  'BsCupHot',
  'BsCupFill',
  'BsEggFried',
  'BsEgg',
  'BsCake',
  'BsCake2',
  'BsCookie',
  'BsApple',
  'BsDroplet',
  'BsDropletHalf',
  'BsDropletFill',
  'BsWater',
  // Health & beauty
  'BsHeart',
  'BsHeartFill',
  'BsHeartPulse',
  'BsCapsule',
  'BsCapsulePill',
  'BsBandaid',
  'BsBandaidFill',
  'BsHospital',
  'BsActivity',
  'BsPrescription2',
  'BsPersonHeart',
  'BsEmojiSmile',
  'BsEmojiLaughing',
  // Home & garden
  'BsHouse',
  'BsHouseDoor',
  'BsHouseHeart',
  'BsBuilding',
  'BsBuildings',
  'BsDoorOpen',
  'BsLamp',
  'BsLampFill',
  'BsLightbulb',
  'BsLightbulbFill',
  'BsFan',
  'BsTree',
  'BsFlower1',
  'BsFlower2',
  'BsFlower3',
  'BsBucket',
  'BsHammer',
  'BsTools',
  'BsWrench',
  'BsScrewdriver',
  'BsGear',
  'BsGearFill',
  'BsNut',
  'BsSliders',
  // Retail & shopping
  'BsShop',
  'BsShopWindow',
  'BsBasket',
  'BsBasket2',
  'BsBasket3',
  'BsCart',
  'BsCart2',
  'BsCart3',
  'BsCart4',
  'BsCartCheck',
  'BsBox',
  'BsBoxSeam',
  'BsBox2',
  'BsArchive',
  'BsInboxes',
  'BsTag',
  'BsTags',
  'BsBookmark',
  'BsBookmarkStar',
  'BsStar',
  'BsStarFill',
  'BsGift',
  'BsGiftFill',
  'BsBalloon',
  'BsBalloonFill',
  'BsBalloonHeart',
  'BsBalloonHeartFill',
  'BsTrophy',
  'BsAward',
  'BsReceipt',
  'BsReceiptCutoff',
  'BsTicket',
  'BsTicketPerforated',
  'BsPercent',
  'BsPatchCheck',
  'BsPatchPlus',
  // Transport & travel
  'BsCarFront',
  'BsCarFrontFill',
  'BsTruck',
  'BsBusFront',
  'BsBicycle',
  'BsScooter',
  'BsTrainFront',
  'BsAirplane',
  'BsRocket',
  'BsSuitcase',
  'BsSuitcase2',
  'BsBriefcase',
  'BsBriefcaseFill',
  'BsGlobe',
  'BsGlobe2',
  'BsGeoAlt',
  'BsCompass',
  'BsPinMap',
  'BsSignpost',
  'BsSignpost2',
  // Office & stationery
  'BsBook',
  'BsJournal',
  'BsJournalText',
  'BsNewspaper',
  'BsFileText',
  'BsFolder',
  'BsFolder2',
  'BsPencil',
  'BsPen',
  'BsRulers',
  'BsClipboard',
  'BsClipboardCheck',
  'BsPaperclip',
  'BsEnvelope',
  'BsEnvelopeOpen',
  // People & services
  'BsPerson',
  'BsPeople',
  'BsPersonBadge',
  'BsPersonWorkspace',
  'BsTelephone',
  'BsChat',
  'BsChatDots',
  'BsMegaphone',
  'BsBadgeAd',
  // Money & business
  'BsCash',
  'BsCashStack',
  'BsCoin',
  'BsCreditCard',
  'BsCreditCard2Front',
  'BsBank',
  'BsWallet',
  'BsWallet2',
  'BsPiggyBank',
  'BsCurrencyDollar',
  'BsCurrencyEuro',
  'BsCurrencyPound',
  'BsGraphUp',
  'BsGraphDown',
  'BsBarChart',
  'BsPieChart',
  // Security & utilities
  'BsShield',
  'BsShieldCheck',
  'BsLock',
  'BsKey',
  'BsFingerprint',
  'BsFire',
  'BsSnow',
  'BsSnow2',
  'BsCloud',
  'BsCloudRain',
  'BsSun',
  'BsMoon',
  'BsUmbrella',
  'BsThermometer',
  'BsThermometerHalf',
  'BsWind',
  // Media & entertainment
  'BsImage',
  'BsImages',
  'BsFilm',
  'BsPlay',
  'BsDice5',
  'BsDice6',
  'BsPuzzle',
  'BsDribbble',
  // Misc & UI
  'BsSearch',
  'BsFilter',
  'BsList',
  'BsGrid',
  'BsGrid3X3',
  'BsLayers',
  'BsCollection',
  'BsCalendar',
  'BsCalendarEvent',
  'BsClock',
  'BsAlarm',
  'BsStopwatch',
  'BsLink45Deg',
  'BsRecycle',
  'BsTrash',
  'BsTrash3',
  'BsPlus',
  'BsCheck2',
];

export function isBsIconName(value) {
  return typeof value === 'string' && /^Bs[A-Z]/.test(value);
}

export function resolveCategoryIconKey(stored, categories = [], categoryId = null) {
  if (isBsIconName(stored)) return stored;
  if (categoryId != null && categories.length) {
    const cat = categories.find((c) => String(c.id) === String(categoryId));
    if (cat?.icon && isBsIconName(cat.icon)) return cat.icon;
  }
  return DEFAULT_CATEGORY_ICON;
}
